# Multiclass SVM 구현

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score

#IRIS 데이터 로드
iris =  sns.load_dataset('iris') 
X= iris.iloc[:,:4] #학습할데이터
y = iris.iloc[:,-1] #타겟
print(y)

0         setosa
1         setosa
2         setosa
3         setosa
4         setosa
         ...    
145    virginica
146    virginica
147    virginica
148    virginica
149    virginica
Name: species, Length: 150, dtype: object


In [2]:
X

sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=48)

In [7]:
y_setosa = y_train.apply(lambda x : 1 if x=='setosa' else 0)
y_versicolor = y_train.apply(lambda x : 1 if x=='versicolor' else 0)
y_virginica = y_train.apply(lambda x : 1 if x=='virginica' else 0)

In [8]:
def standardization(train, test):
    scaler = StandardScaler()
    train = scaler.fit_transform(train)
    test = scaler.transform(test)
    return train, test

X_train, X_test = standardization(X_train, X_test)

In [9]:
X_train

array([[ 0.78522493,  0.32015325,  0.77221097,  1.04726529],
       [-0.26563371, -1.29989934,  0.0982814 , -0.11996537],
       [ 0.43493872,  0.78302542,  0.94069336,  1.43634218],
       [-0.84944407,  0.78302542, -1.24957775, -1.28719604],
       [-0.38239578, -1.7627715 ,  0.15444219,  0.13941922],
       [ 0.55170079, -0.374155  ,  1.05301496,  0.7878807 ],
       [ 0.31817664, -0.14271892,  0.65988937,  0.7878807 ],
       [ 0.20141457, -0.374155  ,  0.43524618,  0.39880381],
       [-1.66677857, -0.14271892, -1.36189934, -1.28719604],
       [-0.14887164, -0.60559109,  0.21060299,  0.13941922],
       [-0.14887164, -1.06846325, -0.12636179, -0.24965767],
       [ 0.31817664, -0.60559109,  0.15444219,  0.13941922],
       [ 0.66846286, -0.83702717,  0.88453256,  0.91757299],
       [ 0.0846525 , -0.14271892,  0.77221097,  0.7878807 ],
       [-0.49915786, -0.14271892,  0.43524618,  0.39880381],
       [-0.26563371, -0.60559109,  0.65988937,  1.04726529],
       [ 2.18636979,  1.

In [10]:
X_test

array([[-0.14887164, -0.374155  ,  0.26676379,  0.13941922],
       [ 0.31817664, -0.60559109,  0.54756778,  0.00972692],
       [ 0.31817664, -1.06846325,  1.05301496,  0.26911151],
       [-1.5500165 , -1.7627715 , -1.36189934, -1.15750374],
       [ 0.0846525 ,  0.32015325,  0.60372857,  0.7878807 ],
       [ 0.78522493, -0.14271892,  0.99685416,  0.7878807 ],
       [-0.84944407,  1.70876975, -1.24957775, -1.15750374],
       [ 0.20141457, -0.14271892,  0.60372857,  0.7878807 ],
       [-0.38239578,  2.63451409, -1.30573855, -1.28719604],
       [-0.38239578, -1.29989934,  0.15444219,  0.13941922],
       [ 0.66846286,  0.08871717,  0.99685416,  0.7878807 ],
       [-0.38239578,  1.0144615 , -1.36189934, -1.28719604],
       [-0.49915786,  0.78302542, -1.13725615, -1.28719604],
       [ 0.43493872, -0.60559109,  0.60372857,  0.7878807 ],
       [ 0.55170079, -1.7627715 ,  0.37908538,  0.13941922],
       [ 0.55170079,  0.55158933,  0.54756778,  0.52849611],
       [-1.19973028,  0.

In [21]:
svc1 = SVC(kernel='linear', C = 100)
svc2 = SVC(kernel='linear', C = 100)
svc3 = SVC(kernel='linear', C = 100)

svc1.fit(X_train,y_setosa) 
svc2.fit(X_train,y_versicolor) 
svc3.fit(X_train,y_virginica) 

SVC(C=1)

In [22]:
pred1 = svc1.predict(X_test)
pred2 = svc2.predict(X_test)
pred3 = svc3.predict(X_test)

In [23]:
svc1.decision_function(X_test)

array([-1.12800812, -1.16251843, -1.1422978 , -0.08568098, -1.17027451,
       -1.23267582,  1.09183692, -1.2512859 ,  1.02069728, -1.2643363 ,
       -1.23088294,  1.10969518,  1.09329371, -1.25623518, -1.04702622,
       -1.12673257,  1.1923107 , -1.02360898, -1.15249844, -1.1523064 ,
        0.88066583, -1.22401144, -1.21240853, -1.14948774, -1.13066337,
        1.17327079,  1.04484236, -1.03358459, -1.13006558, -1.02256327])

In [29]:
print(pred1)
print(pred2)
print(pred3)

[0 0 0 0 0 0 1 0 1 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 0 1 1 0 0 0]
[1 1 0 0 1 0 0 0 0 1 0 0 0 0 1 1 0 1 1 0 0 0 1 1 0 0 0 0 0 1]
[0 0 1 0 0 1 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 1 0 1 0 0 1 1 0]


3개다 0인 경우 존재

In [31]:
print(svc1.decision_function(X_test))
print(svc2.decision_function(X_test))
print(svc3.decision_function(X_test))

[-1.12800812 -1.16251843 -1.1422978  -0.08568098 -1.17027451 -1.23267582
  1.09183692 -1.2512859   1.02069728 -1.2643363  -1.23088294  1.10969518
  1.09329371 -1.25623518 -1.04702622 -1.12673257  1.1923107  -1.02360898
 -1.15249844 -1.1523064   0.88066583 -1.22401144 -1.21240853 -1.14948774
 -1.13066337  1.17327079  1.04484236 -1.03358459 -1.13006558 -1.02256327]
[ 1.22902861  1.18021327 -0.17897727 -0.18270157  0.11157081 -0.62302972
 -1.30208112 -0.1161839  -1.11408288  0.98146982 -0.50352989 -1.22949294
 -1.09831885 -0.35890882  0.58081027  0.69274083 -1.43031588  1.07405999
  0.047718   -1.42480972 -1.11371034 -0.89665337  0.04194481  0.8041226
 -0.32973119 -1.43978879 -1.02086281 -1.26618241 -1.86832122  1.23359629]
[-1.42708779 -1.21748862  0.15658044 -0.9341312  -0.13715909  0.77015558
 -1.1852678   0.18563113 -1.0405367  -0.99876073  0.64733162 -1.33283373
 -1.49025247  0.45890847 -0.65925536 -0.69718272 -1.26836718 -1.17659977
 -0.03926931  1.53339216 -1.12083008  1.03585352  

각 값에 대하여 가장 decision function이 큰 값을 선택

In [38]:
result = []
a = svc1.decision_function(X_test)
b = svc2.decision_function(X_test)
c = svc3.decision_function(X_test)

for setosa, versicolor, virginica in zip(a, b, c):
    temp = [setosa, versicolor, virginica]
    max_decision = max(temp)
    if max_decision == temp[0]:
        result.append('setosa')
    elif max_decision == temp[1]:
        result.append('versicolor')
    else:
        result.append('virginica')

result = np.array(result)

In [39]:
result

array(['versicolor', 'versicolor', 'virginica', 'setosa', 'versicolor',
       'virginica', 'setosa', 'virginica', 'setosa', 'versicolor',
       'virginica', 'setosa', 'setosa', 'virginica', 'versicolor',
       'versicolor', 'setosa', 'versicolor', 'versicolor', 'virginica',
       'setosa', 'virginica', 'virginica', 'versicolor', 'virginica',
       'setosa', 'setosa', 'virginica', 'virginica', 'versicolor'],
      dtype='<U10')

In [41]:
accuracy_score(y_test, result)

0.9666666666666667